- name: Home
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  columns:
    - size: full
      widgets:
        - type: group
          widgets:
            - type: hacker-news
            - type: lobsters
            - type: bookmarks
              groups:
                - title: Telegram Channels
                  color: 200 78 52
                  links:
                    - title: LLL [atolstikov]
                      url: https://t.me/LLL_atolstikov
                      icon: si:telegram
                    - title: melikhov.dev
                      url: https://t.me/melikhov_dev
                      icon: si:telegram
                    - title: this->notes.
                      url: https://t.me/thisnotes
                      icon: si:telegram
                    - title: Технопродакт
                      url: https://t.me/ruslanxtech
                      icon: si:telegram
                    - title: Teamlead Bootcamp [Chat]
                      url: https://t.me/tlbootcamp
                      icon: si:telegram
                      
    - size: full
      widgets:
        - type: videos
          style: grid-cards
          channels:
            - UCbRP3c757lWg9M-U7TyEkXA # Theo
            - UCsBjURrPoezykLs9EqgamOA # Fireship
            - UC2Jwo4Q0s-ucjGseHP8XUSQ # HolyJs
            - UCUyeluBRhGPCW4rPe_UvBZQ # ThePrimeTime
            - UC2Xd-TjJByJyK2w1zNwY0zQ # Beyond Fireship
            - UChk6TQce1EJMn6_liKdHDog # ThePrimeagenClips
            - UCIjIAXXsX4YMYeFj-LP42-Q # Anthony GG
